name: github_search
description: Github Search
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  webview_flutter: ^1.0.7
  get: ^3.25.6
  kayta:
    git:
      url: git://github.com/bernardoveras/kayta.git
  responsive_framework: ^0.0.14
  font_awesome_flutter: ^8.11.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  mockito: ^4.1.4
  faker: ^1.3.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo-horizontal.png
    - assets/images/logo-vertical.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700